### ISSUE TITLE
Fix login page

### ISSUE THREAD

**Issue by apux** [LogicalBricks/prev#7]
Devise tries to show some links whose paths aren't available in the system. Overwrite the views and remove these links.

**Comment by thotmx** [comment]
We need to generate the devise views to avoid it. @apux. Is it ok?

**Comment by apux** [comment]
I think so. I don't know if devise includes another way to customise it (a configuration file or something like this).

**Comment by thotmx** [comment]
Please, @apux @fervisa take a look to the quickfix. Maybe it's enough with that.

**Comment by apux** [comment]
It would be ok for this issue. I'll open a new one for the view, layout, etc.
